"""Paderborn University KAt-DataCenter bearing adapter (fault diagnosis /
condition monitoring, NOT run-to-failure). Source and verification:
docs/external-datasets.md.

Each file is one short (4s) fixed-condition recording - speed/torque/radial
force combination, named `N<speed>_M<torque>_F<force>_<bearing_code>_<run>.mat`
(e.g. `N15_M07_F10_KA01_1.mat`). There is no elapsed-time axis across a
degradation trajectory and no true RUL target, even for the "real damage"
bearing codes generated by accelerated lifetime testing - each individual
recording is still a snapshot of the bearing's condition at that moment, not
a position on a run-to-failure curve.

File format: MATLAB v5, one top-level struct named identically to the file
(minus extension), with fields `Info`/`X`/`Y`/`Description`. `Y` is an array
of per-channel structs (`Name`, `Data`, `Unit`, ...) - this module reads the
`vibration_1` channel, 256,000 samples at 64 kHz (4s), the channel the
published literature (Lessmeier et al. 2016) centers fault-diagnosis
features on.

Dataset-specific parsing only - no feature formulas live here (features.py's
job, same adapter boundary as femto.py/college.py/ims.py/cwru.py).
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import scipy.io as sio

from bearing_pdm.features import frequency_domain_features, time_domain_features

DATASET_TYPE = "FAULT_DIAGNOSIS"  # never RUN_TO_FAILURE_RUL - see module docstring

VIBRATION_SAMPLE_RATE_HZ = 64_000.0  # 256,000 samples / 4s recording, confirmed from real files

_FILENAME_RE = re.compile(r"^N(\d+)_M(\d+)_F(\d+)_([A-Za-z0-9]+)_(\d+)$")


def parse_filename(path: str | Path) -> dict[str, str]:
    """speed/torque/force/bearing_code/run, parsed from the file's own name -
    never inferred from folder position."""
    stem = Path(path).stem
    m = _FILENAME_RE.match(stem)
    if not m:
        raise ValueError(f"{path}: filename does not match N<speed>_M<torque>_F<force>_<code>_<run>")
    speed, torque, force, code, run = m.groups()
    return {"speed_code": speed, "torque_code": torque, "force_code": force,
            "bearing_code": code, "run": run}


def read_channel(path: str | Path, channel: str = "vibration_1") -> np.ndarray:
    """One channel's time-domain signal as float64, shape (n_samples,).

    Reads the top-level struct (named identically to the file) and searches
    its `Y` array of channel structs for the one whose `Name` matches -
    never assumes channel ordering/position within `Y`.
    """
    stem = Path(path).stem
    data = sio.loadmat(str(path), struct_as_record=False, squeeze_me=True)
    if stem not in data:
        raise ValueError(f"{path}: expected top-level struct {stem!r}, found {list(data.keys())}")
    top = data[stem]
    for item in top.Y:
        if item.Name == channel:
            return np.asarray(item.Data, dtype="float64").ravel()
    available = [item.Name for item in top.Y]
    raise ValueError(f"{path}: channel {channel!r} not found (available: {available})")


def extract_features(path: str | Path, sample_rate_hz: float = VIBRATION_SAMPLE_RATE_HZ) -> dict[str, float]:
    """Time- and frequency-domain features for one recording's vibration_1
    channel, using the SAME formulas (features.py) the FEMTO/college/IMS/CWRU
    adapters use, keyed as `vibration_x_*` so the result lines up with
    ApplicabilityModel.feature_columns. Paderborn has only this one
    accelerometer channel per recording (no second radial axis the way
    FEMTO does) - there is no `vibration_y_*` here."""
    signal = read_channel(path)
    features: dict[str, float] = {}
    features.update(time_domain_features(signal, "vibration_x"))
    features.update(frequency_domain_features(signal, sample_rate_hz, "vibration_x"))
    return features
