"use client";

import { useState } from "react";
import { ExplainResponse, PredictRulResponse, explainPrediction } from "@/lib/api";

/**
 * Defensive cleanup only - the system prompt (src/bearing_pdm/rag/explain.py
 * SYSTEM_PROMPT) already asks the model for plain text. This strips Markdown
 * markers that slip through anyway (asterisks, headings, lettered points)
 * without rewriting wording, so the UI never shows raw "**" or "##".
 */
export function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s*/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/^\s*[-*]\s+/gm, "")
    .replace(/^\s*\(?[a-z]\)\s*/gim, "")
    .replace(/\s*\([a-c]\):?/g, "")
    // Some online providers inject their own inline citation markers (e.g.
    // "【Document Title | chunk doc_x:0012:hash】") despite the system prompt
    // asking for plain text - found live on the Vercel Preview. Citations
    // are already shown in their own "Sources" list below the explanation,
    // so this inline form is pure noise, never unique information.
    .replace(/【[^】]*】/g, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

type ExplainUiState =
  | { phase: "ready" }
  | { phase: "generating" }
  | { phase: "complete"; data: ExplainResponse }
  | { phase: "error"; message: string };

/**
 * M7 explanation layer (docs/rag.md), shown underneath an already-computed
 * RUL result. This component never computes or displays a number of its
 * own - it only asks the backend to explain the result passed in via
 * `result`. The primary RUL card above this stays the ML model output
 * (goals.md #15).
 */
export function ExplainResult({ result }: { result: Partial<PredictRulResponse> }) {
  const [open, setOpen] = useState(false);
  const [state, setState] = useState<ExplainUiState>({ phase: "ready" });
  const [question, setQuestion] = useState("");

  async function runExplain() {
    setState({ phase: "generating" });
    try {
      const data = await explainPrediction(result, question);
      setState({ phase: "complete", data });
    } catch (err) {
      setState({
        phase: "error",
        message: err instanceof Error ? err.message : "Explanation request failed.",
      });
    }
  }

  return (
    <div className="mt-2">
      <button
        type="button"
        onClick={() => {
          setOpen((v) => !v);
          if (!open && state.phase === "ready") void runExplain();
        }}
        className="text-xs font-medium text-foreground-muted underline hover:text-foreground"
      >
        {open ? "Hide explanation" : "Explain this result"}
      </button>

      {open && (
        <div className="mt-2 rounded-lg border border-surface-border bg-surface p-3 text-xs">
          <p className="mb-2 font-medium text-foreground-muted">Result explanation</p>

          {state.phase === "generating" && <p>Retrieving evidence and generating explanation…</p>}

          {state.phase === "error" && (
            <div className="flex flex-col gap-2">
              <p className="text-danger">Provider unavailable: {state.message}</p>
              <button
                type="button"
                onClick={() => void runExplain()}
                className="self-start rounded border border-surface-border px-2 py-1"
              >
                Retry
              </button>
            </div>
          )}

          {state.phase === "complete" && (
            <div className="flex flex-col gap-2">
              {state.data.status === "insufficient_evidence" && (
                <p className="italic text-foreground-muted">
                  No indexed source closely matched this question - showing the model result only.
                </p>
              )}
              <p className="whitespace-pre-line leading-relaxed">
                {stripMarkdown(state.data.explanation)}
              </p>
              {state.data.citations.length > 0 && (
                <div>
                  <p className="font-medium text-foreground-muted">Sources</p>
                  <ul className="list-inside list-disc">
                    {state.data.citations.map((c) => (
                      <li key={c.chunk_id}>
                        {c.document_title} (relevance {c.relevance_score.toFixed(2)})
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              <p className="text-foreground-muted">
                Generated by: {state.data.provider}
                {state.data.fallback_used && " (deterministic fallback - no online LLM configured)"}
              </p>
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  void runExplain();
                }}
                className="mt-1 flex gap-2"
              >
                <input
                  value={question}
                  onChange={(e) => setQuestion(e.target.value)}
                  placeholder="Ask a follow-up question (optional)"
                  className="flex-1 rounded border border-surface-border bg-background px-2 py-1 text-xs"
                />
                <button type="submit" className="rounded border border-surface-border px-2 py-1">
                  Ask
                </button>
              </form>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
