#!/usr/bin/env python
"""Precompute a compact, committed summary of fault-diagnosis-only external
datasets (CWRU today) for the /evaluation/cross-dataset endpoint and the
Next.js cross-dataset page - same pattern as build_trajectory_data.py /
build_college_trajectory.py: compute once from real data, commit the small
derived JSON, never refit or re-score on request.

CWRU has no run-to-failure RUL target (docs/external-datasets.md) - this
artifact intentionally carries NO mae_seconds/rul fields, only dataset
profile + a real applicability check against the frozen FEMTO model, so
nothing downstream can mistakenly average it into the RUL comparison table.

Usage (repo root): PYTHONPATH=src python scripts/build_fault_diagnosis_profile.py
"""

from __future__ import annotations

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from bearing_pdm.applicability import assess as applicability_assess
from bearing_pdm.cwru import DATASET_TYPE as CWRU_DATASET_TYPE
from bearing_pdm.cwru import extract_features as cwru_extract_features
from bearing_pdm.paderborn import DATASET_TYPE as PADERBORN_DATASET_TYPE
from bearing_pdm.paderborn import VIBRATION_SAMPLE_RATE_HZ as PADERBORN_SAMPLE_RATE_HZ
from bearing_pdm.paderborn import extract_features as paderborn_extract_features
from bearing_pdm.routing import candidates_from_bundle

REPO_ROOT = Path(__file__).resolve().parents[1]
CWRU_FIXTURES = REPO_ROOT / "data" / "fixtures" / "cwru"
PADERBORN_FIXTURES = REPO_ROOT / "data" / "fixtures" / "paderborn"
BUNDLE_PATH = REPO_ROOT / "artifacts" / "models" / "cross_domain_bundle.joblib"
OUT_PATH = REPO_ROOT / "deploy_data" / "fault_diagnosis_datasets.json"

CWRU_FILES = {
    "97": "normal baseline",
    "105": "inner race fault 0.007in",
    "118": "ball fault 0.007in",
    "130": "outer race fault 0.007in @6:00",
}
CWRU_SAMPLE_RATE_HZ = 12_000.0

PADERBORN_FILES = {
    "N15_M07_F10_K001_1": "healthy (K001)",
    "N15_M07_F10_KA01_1": "artificial outer-race fault (KA01)",
}


def _load_femto_applicability_model():
    if not BUNDLE_PATH.exists():
        return None
    bundle = joblib.load(BUNDLE_PATH)
    candidates = [c for c in candidates_from_bundle(bundle) if c.name == "raw_seconds"]
    return candidates[0].applicability if candidates else None


def build_cwru_entry(model) -> dict:
    entry: dict = {
        "dataset": "CWRU (Case Western Reserve University Bearing Data Center)",
        "dataset_type": CWRU_DATASET_TYPE,
        "source": "https://engineering.case.edu/bearingdatacenter/download-data-file",
        "sampling_rate_hz": CWRU_SAMPLE_RATE_HZ,
        "channels": ["vibration_x (drive-end accelerometer)"],
        "conditions": [{"file_id": k, "label": v} for k, v in CWRU_FILES.items()],
        "rul_supported": False,
        "rul_unavailable_reason": (
            "CWRU records single fixed-condition snapshots, not a degradation "
            "trajectory - there is no elapsed-time axis and no true RUL target."
        ),
        "applicability": None,
    }
    if model is None:
        entry["applicability_unavailable_reason"] = "cross_domain_bundle.joblib not present/usable at build time"
        return entry

    rows = []
    for file_id in CWRU_FILES:
        features = cwru_extract_features(
            CWRU_FIXTURES / f"{file_id}.mat", file_id, sample_rate_hz=CWRU_SAMPLE_RATE_HZ
        )
        rows.append({c: features.get(c, np.nan) for c in model.feature_columns})
    df = pd.DataFrame(rows, dtype=float)
    result = applicability_assess(df, model, single_recording=False)
    entry["applicability"] = {
        "level": result["level"],
        "shift_ratio": result["shift_ratio"],
        "reasons": result["reasons"],
        "evaluated_against": "artifacts/models/cross_domain_bundle.joblib (frozen FEMTO model)",
    }
    return entry


def build_paderborn_entry(model) -> dict:
    entry: dict = {
        "dataset": "Paderborn University KAt-DataCenter",
        "dataset_type": PADERBORN_DATASET_TYPE,
        "source": "https://groups.uni-paderborn.de/kat/BearingDataCenter/",
        "sampling_rate_hz": PADERBORN_SAMPLE_RATE_HZ,
        "channels": ["vibration_x (vibration_1 accelerometer)"],
        "conditions": [{"file_id": k, "label": v} for k, v in PADERBORN_FILES.items()],
        "rul_supported": False,
        "rul_unavailable_reason": (
            "Each Paderborn recording is a short (4s) fixed-condition snapshot, not a "
            "degradation trajectory - there is no elapsed-time axis and no true RUL target, "
            "even for the real-damage bearing codes generated by accelerated lifetime testing."
        ),
        "applicability": None,
    }
    if model is None:
        entry["applicability_unavailable_reason"] = "cross_domain_bundle.joblib not present/usable at build time"
        return entry

    rows = []
    for file_id in PADERBORN_FILES:
        features = paderborn_extract_features(
            PADERBORN_FIXTURES / f"{file_id}.mat", sample_rate_hz=PADERBORN_SAMPLE_RATE_HZ
        )
        rows.append({c: features.get(c, np.nan) for c in model.feature_columns})
    df = pd.DataFrame(rows, dtype=float)
    result = applicability_assess(df, model, single_recording=False)
    entry["applicability"] = {
        "level": result["level"],
        "shift_ratio": result["shift_ratio"],
        "reasons": result["reasons"],
        "evaluated_against": "artifacts/models/cross_domain_bundle.joblib (frozen FEMTO model)",
    }
    return entry


def main() -> None:
    model = _load_femto_applicability_model()
    payload = {
        "cwru": build_cwru_entry(model),
        "paderborn": build_paderborn_entry(model),
    }
    OUT_PATH.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(f"Wrote {OUT_PATH}")
    for name, entry in payload.items():
        print(name, json.dumps(entry.get("applicability"), indent=2))


if __name__ == "__main__":
    main()
