import { test, expect } from "@playwright/test";

// Golden-path + key-state smoke coverage across desktop and 390px mobile
// (see playwright.config.ts projects). Runs against a live backend so the
// FEMTO sample-data prediction is a real model call, not a mock.

test("home links to Analyze", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("link", { name: /analyze/i }).first().click();
  await expect(page).toHaveURL(/\/upload/);
});

test("trusted FEMTO sample produces a HIGH-applicability RUL result", async ({ page }) => {
  await page.goto("/upload");
  await page.getByRole("button", { name: /try sample data/i }).click();
  await expect(page.getByText(/hours/)).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/model applicability: high/i)).toBeVisible();
});

test("invalid upload shows a readable error, not a crash", async ({ page }) => {
  await page.goto("/upload");
  await page.setInputFiles('[data-testid="file-input"]', {
    name: "garbage.csv",
    mimeType: "text/csv",
    buffer: Buffer.from("not,numeric,data\nfoo,bar,baz\n"),
  });
  await page.getByRole("button", { name: /analyze bearing/i }).click();
  await expect(page.getByText(/won't succeed on retry|error|RUL suppressed/i)).toBeVisible({
    timeout: 20_000,
  });
});

test("Advanced Predict page links back to Analyze", async ({ page }) => {
  await page.goto("/predict");
  await expect(page.getByText(/Advanced Tool — Direct Model Input/)).toBeVisible();
  await page.getByRole("link", { name: /analyze a raw bearing file instead/i }).click();
  await expect(page).toHaveURL(/\/upload/);
});

test("Advanced Degradation page links back to Analyze", async ({ page }) => {
  await page.goto("/degradation");
  await expect(page.getByText(/Advanced Tool — Health Indicator/)).toBeVisible();
  await page.locator("main").getByRole("link", { name: "Analyze" }).click();
  await expect(page).toHaveURL(/\/upload/);
});

test("Reliability/evaluation page loads without a 5xx", async ({ page }) => {
  const response = await page.goto("/evaluation");
  expect(response?.status()).toBeLessThan(500);
});

test("Explain this result shows a grounded AI Maintenance Explanation with citations", async ({
  page,
}) => {
  await page.goto("/upload");
  await page.getByRole("button", { name: /try sample data/i }).click();
  await expect(page.getByText(/hours/)).toBeVisible({ timeout: 20_000 });
  await page.getByRole("button", { name: /explain this result/i }).click();
  await expect(page.getByText(/AI Maintenance Explanation/i)).toBeVisible();
  await expect(page.getByText(/Generated by:/i)).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/model result/i)).toBeVisible();

  // Section 12 regression: no raw Markdown artifacts rendered to the user.
  const bodyText = await page.locator("main").innerText();
  expect(bodyText).not.toMatch(/\*\*/);
  expect(bodyText).not.toMatch(/^##/m);
});

test("Signal & FFT / Features tabs render real data from the uploaded sample", async ({ page }) => {
  await page.goto("/upload");
  await page.getByRole("button", { name: /try sample data/i }).click();
  await expect(page.getByText(/hours/)).toBeVisible({ timeout: 20_000 });

  await expect(page.getByText(/samples at [\d,]+ Hz/i)).toBeVisible({ timeout: 20_000 });
  await page.getByRole("button", { name: "Features", exact: true }).click();
  await expect(page.getByText(/rms/i).first()).toBeVisible();
});

test("Explore Bearing Trajectory shows HI, stage, and held-out RUL for Bearing2_1", async ({
  page,
}) => {
  await page.goto("/trajectory");
  await page.getByRole("combobox").selectOption({ label: "femto:Bearing2_1" });
  await expect(page.getByText(/HEALTHY|DEGRADING|CRITICAL/).first()).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/severity band.*not a physical fault diagnosis/i)).toBeVisible();
  await expect(page.getByText(/MAE/i).first()).toBeVisible();
});

test("Evaluation page shows the college case study with the naive-oracle caveat", async ({ page }) => {
  await page.goto("/evaluation");
  await expect(page.getByText(/College case study/i)).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/domain-shift limitation/i)).toBeVisible();
});

test("Datasets explorer shows real FEMTO/College/IMS/CWRU/Paderborn cards and a separated Synthetic card, with no fabricated RUL", async ({
  page,
}) => {
  const consoleErrors: string[] = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") consoleErrors.push(msg.text());
  });

  await page.goto("/datasets");
  await expect(page.getByText("FEMTO/PRONOSTIA")).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/College run-to-failure/)).toBeVisible();
  await expect(page.getByText(/IMS \/ NASA/)).toBeVisible();
  await expect(page.getByText(/CWRU \(Case Western/)).toBeVisible();
  await expect(page.getByText(/Paderborn University/)).toBeVisible();
  await expect(page.getByText("Synthetic bearing degradation simulator")).toBeVisible();

  // CWRU/Paderborn must never show a fabricated RUL metric.
  await expect(page.getByText("RUL evaluation unavailable.").first()).toBeVisible();
  const bodyText = await page.locator("main").innerText();
  expect(bodyText).not.toMatch(/RUL MAE|RUL RMSE/i);

  // Synthetic must be visually/textually separated from real data.
  await expect(page.getByText("SYNTHETIC", { exact: true })).toBeVisible();
  await expect(page.getByText(/NOT REAL-WORLD VALIDATION/)).toBeVisible();

  expect(consoleErrors, `unexpected console errors: ${consoleErrors.join("; ")}`).toEqual([]);
});

test("Cross-dataset page renders grouped sections without a 5xx or crash", async ({ page }) => {
  const response = await page.goto("/cross-dataset");
  expect(response?.status()).toBeLessThan(500);
  await expect(page.getByText("Cross-dataset comparison")).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/must never be averaged/i)).toBeVisible();
});

test.describe("no horizontal page overflow at mobile width", () => {
  // Regression: <main> (a flex child of body's `flex flex-col`) was missing an
  // explicit w-full, so on pages with a wide table or an unbroken long string
  // (a file path, a source URL) it grew past the viewport instead of shrinking
  // to it - real horizontal scroll on /evaluation, /cross-dataset, and
  // /datasets, confirmed via document.documentElement.scrollWidth. Fixed by
  // adding w-full to every page's <main>, wrapping the two bare <table>s on
  // /evaluation in overflow-x-auto (matching the pattern /cross-dataset's
  // table already used), and break-words/break-all on the long strings.
  for (const path of ["/", "/upload", "/evaluation", "/datasets", "/cross-dataset", "/trajectory"]) {
    test(path, async ({ page }) => {
      await page.goto(path);
      await page.waitForTimeout(1000);
      const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
      const clientWidth = await page.evaluate(() => document.documentElement.clientWidth);
      expect(scrollWidth).toBeLessThanOrEqual(clientWidth + 2);
    });
  }
});

test("Generic non-FEMTO CSV is treated as out-of-distribution, not a FEMTO prediction", async ({
  page,
}) => {
  // Real college LogFile_*.csv files are ~137MB each (full-run vibration capture) -
  // impractical for an E2E upload. A small, structurally-valid but non-FEMTO-shaped
  // CSV (same column names college/generic data use, no FEMTO header) exercises the
  // same RETRAIN_REQUIRED/suppression path the frontend's handleGenericFile takes.
  await page.goto("/upload");
  await page.setInputFiles('[data-testid="file-input"]', {
    name: "generic-vibration.csv",
    mimeType: "text/csv",
    buffer: Buffer.from(
      "vibration_x,vibration_y\n" + Array.from({ length: 50 }, () => "0.1,0.2").join("\n") + "\n",
    ),
  });
  await page.getByRole("button", { name: /analyze bearing/i }).click();
  await expect(
    page.getByText(
      /RUL suppressed|outside the training distribution|RETRAIN_REQUIRED|won't succeed on retry/i,
    ),
  ).toBeVisible({ timeout: 20_000 });
});
